### ISSUE TITLE
Ubuntu: Error when presenting numerical data on a sketchpad

### ISSUE THREAD

**Issue by lindenloot** [smathot/osweb#44] opened 2020-11-18 19:23 UTC
Version:
- OpenSesame 3.3.5 Lentiform Loewenfeld

Platforms tested:
- Ubuntu 20.04.1 LTS
- Windows 10

Backends tested:
- Legacy
- PsychoPy
- PyGame

Issue:
**On Ubuntu**: When trying to present numerical data (int or float) on a sketchpad, OSWeb gives the following error message: 

`Uncaught TypeError: t.replace is not a function`

**On Windows**: It works fine

**Comment by smathot** [comment] 2020-11-19 10:18
This sort of looks like a duplicate of #40, although there the error message refers to `txt.replace` (rather than `t.replace`). Which version of OSWeb are you using on Ubuntu?

**Closed as completed** 2020-11-29 11:18 UTC
Labels: bug
