### ISSUE TITLE
Response items do not suffix item names to response variables

### ISSUE THREAD

**Issue by dschreij** [smathot/osweb#22] opened 2020-06-18 12:36 UTC
touch_response items do not store the usual vars that an item logs, such as `correct_<item_name>` or `response_time_<item_name>`. See https://forum.cogsci.nl/discussion/comment/19615/#Comment_19615 for more info and an experiment that demonstrates this.

**Comment by tomcamus** [comment] 2020-06-18 13:01
See here instead for a new post now dedicated to that issue:
https://forum.cogsci.nl/discussion/6243/osweb-touch-screen-not-logging-correct-response

**Comment by smathot** [comment] 2020-08-18 07:41
I have edited the title of the issue, because I believe that this affects all response items.

**Comment by smathot** [comment] 2020-10-14 13:44
As far as I can tell, the issue is actually that the `correct` variable wasn't set, which should be fixed by #22.

**Closed as completed** 2020-11-29 11:18 UTC
Labels: enhancement
