### ISSUE TITLE
Endless loop caused by inline javascript 

### ISSUE THREAD

**Issue by SCgeeker** [smathot/osweb#32] opened 2020-08-20 14:53 UTC
Hi, 

My study has a practice session where participants have to correctly answered all the items. If one item was responded incorrectly, the javascript code will reset the counter and restart the loop. This code works well in OpenSesame, but it can not stop the loop if the participants answered all the responses correctly in the second loop. Here is a short script reproduced the errors in OSWEB 1.3.8:

[OSWEB_loop_control.zip](https://github.com/open-cogsci/osweb/files/5103806/OSWEB_loop_control.zip)

**Comment by smathot** [comment] 2020-08-21 12:46
Thanks for flagging this! I suspect that this is related to #30, although I'm not 100% sure. In any case, we're going to fix that first, and then return here to see whether this also solves your issue, and if not, dive deeper.

**Comment by smathot** [comment] 2020-09-16 12:50
On closer inspection, this is actually a duplicate of #31. Thanks for reporting this, and we'll track the issue further there!

**Closed as completed by smathot** 2020-09-16 12:50 UTC
Labels: bug
