### ISSUE TITLE
Background color ignored when sketchpad is inside coroutine

### ISSUE THREAD

**Issue by dschreij** [smathot/osweb#41] opened 2020-10-30 12:09 UTC
See https://forum.cogsci.nl/discussion/6598/osweb-collecting-keyboard-response-while-presenting-multiple-sketchpads
for a discussion.

A sketchpad that is inside a coroutine always has a black background. It ignores the global background setting of the experiment, and setting a background color explicitly with for instance `set background orange` also does nothing.
The (global) foreground color is processed though.

**Comment by smathot** [comment] 2020-10-31 14:59
I'm assuming that this is an accidental duplicate of #42 .

**Closed as completed by smathot** 2020-10-31 14:59 UTC
Labels: bug
